name: Package VSIX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'   # or your preferred Node.js version

      - name: Install vsce
        run: npm install -g @vscode/vsce --no-optional

      - name: Package Extension
        run: vsce package

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v3
        with:
          name: happy-heart-vsix
          path: '*.vsix'
